<?php

$STRUCTURE = array();

$HOOKS = array(
    array(
        "hook_type"       => "template",
        "action_location" => "standalone_form_fields_head_bottom",
        "function_name"   => "",
        "hook_function"   => "includeStandaloneFiles",
        "priority"        => "50"
    ),
    array(
        "hook_type"       => "template",
        "action_location" => "head_bottom",
        "function_name"   => "",
        "hook_function"   => "includeFiles",
        "priority"        => "50"
    )
);

$FILES = array(
    "LICENSE",
    "README.md",
    "code/Module.class.php",
    "help.php",
    "images/tinymce.png",
    "index.php",
    "lang/en_us.php",
    "library.php",
    "module_config.php",
    "templates/help.tpl",
    "templates/index.tpl",
    "tinymce/jquery.tinymce.min.js",
    "tinymce/langs/readme.md",
    "tinymce/license.txt",
    "tinymce/plugins/advlist/plugin.min.js",
    "tinymce/plugins/anchor/plugin.min.js",
    "tinymce/plugins/autolink/plugin.min.js",
    "tinymce/plugins/autoresize/plugin.min.js",
    "tinymce/plugins/autosave/plugin.min.js",
    "tinymce/plugins/bbcode/plugin.min.js",
    "tinymce/plugins/charmap/plugin.min.js",
    "tinymce/plugins/code/plugin.min.js",
    "tinymce/plugins/codesample/css/prism.css",
    "tinymce/plugins/codesample/plugin.min.js",
    "tinymce/plugins/colorpicker/plugin.min.js",
    "tinymce/plugins/contextmenu/plugin.min.js",
    "tinymce/plugins/directionality/plugin.min.js",
    "tinymce/plugins/emoticons/img/smiley-cool.gif",
    "tinymce/plugins/emoticons/img/smiley-cry.gif",
    "tinymce/plugins/emoticons/img/smiley-embarassed.gif",
    "tinymce/plugins/emoticons/img/smiley-foot-in-mouth.gif",
    "tinymce/plugins/emoticons/img/smiley-frown.gif",
    "tinymce/plugins/emoticons/img/smiley-innocent.gif",
    "tinymce/plugins/emoticons/img/smiley-kiss.gif",
    "tinymce/plugins/emoticons/img/smiley-laughing.gif",
    "tinymce/plugins/emoticons/img/smiley-money-mouth.gif",
    "tinymce/plugins/emoticons/img/smiley-sealed.gif",
    "tinymce/plugins/emoticons/img/smiley-smile.gif",
    "tinymce/plugins/emoticons/img/smiley-surprised.gif",
    "tinymce/plugins/emoticons/img/smiley-tongue-out.gif",
    "tinymce/plugins/emoticons/img/smiley-undecided.gif",
    "tinymce/plugins/emoticons/img/smiley-wink.gif",
    "tinymce/plugins/emoticons/img/smiley-yell.gif",
    "tinymce/plugins/emoticons/plugin.min.js",
    "tinymce/plugins/fullpage/plugin.min.js",
    "tinymce/plugins/fullscreen/plugin.min.js",
    "tinymce/plugins/help/img/logo.png",
    "tinymce/plugins/help/plugin.min.js",
    "tinymce/plugins/hr/plugin.min.js",
    "tinymce/plugins/image/plugin.min.js",
    "tinymce/plugins/imagetools/plugin.min.js",
    "tinymce/plugins/importcss/plugin.min.js",
    "tinymce/plugins/insertdatetime/plugin.min.js",
    "tinymce/plugins/legacyoutput/plugin.min.js",
    "tinymce/plugins/link/plugin.min.js",
    "tinymce/plugins/lists/plugin.min.js",
    "tinymce/plugins/media/plugin.min.js",
    "tinymce/plugins/nonbreaking/plugin.min.js",
    "tinymce/plugins/noneditable/plugin.min.js",
    "tinymce/plugins/pagebreak/plugin.min.js",
    "tinymce/plugins/paste/plugin.min.js",
    "tinymce/plugins/preview/plugin.min.js",
    "tinymce/plugins/print/plugin.min.js",
    "tinymce/plugins/save/plugin.min.js",
    "tinymce/plugins/searchreplace/plugin.min.js",
    "tinymce/plugins/spellchecker/plugin.min.js",
    "tinymce/plugins/tabfocus/plugin.min.js",
    "tinymce/plugins/table/plugin.min.js",
    "tinymce/plugins/template/plugin.min.js",
    "tinymce/plugins/textcolor/plugin.min.js",
    "tinymce/plugins/textpattern/plugin.min.js",
    "tinymce/plugins/toc/plugin.min.js",
    "tinymce/plugins/visualblocks/css/visualblocks.css",
    "tinymce/plugins/visualblocks/plugin.min.js",
    "tinymce/plugins/visualchars/plugin.min.js",
    "tinymce/plugins/wordcount/plugin.min.js",
    "tinymce/skins/lightgray/content.inline.min.css",
    "tinymce/skins/lightgray/content.min.css",
    "tinymce/skins/lightgray/content.mobile.min.css",
    "tinymce/skins/lightgray/fonts/tinymce-mobile.woff",
    "tinymce/skins/lightgray/fonts/tinymce-small.eot",
    "tinymce/skins/lightgray/fonts/tinymce-small.svg",
    "tinymce/skins/lightgray/fonts/tinymce-small.ttf",
    "tinymce/skins/lightgray/fonts/tinymce-small.woff",
    "tinymce/skins/lightgray/fonts/tinymce.eot",
    "tinymce/skins/lightgray/fonts/tinymce.svg",
    "tinymce/skins/lightgray/fonts/tinymce.ttf",
    "tinymce/skins/lightgray/fonts/tinymce.woff",
    "tinymce/skins/lightgray/img/anchor.gif",
    "tinymce/skins/lightgray/img/loader.gif",
    "tinymce/skins/lightgray/img/object.gif",
    "tinymce/skins/lightgray/img/trans.gif",
    "tinymce/skins/lightgray/skin.min.css",
    "tinymce/skins/lightgray/skin.mobile.min.css",
    "tinymce/themes/inlite/theme.min.js",
    "tinymce/themes/mobile/theme.min.js",
    "tinymce/themes/modern/theme.min.js",
    "tinymce/tinymce.min.js"
);
